- README.md
- docs/commit-workflow.md
- docs/setup-instructions.md
- docs/training/training.md
- docs/using-storybook.md
- packages/storybook-html/src/docs/introduction/welcome.story.mdx
Updates to repo docs -- revised README, moved setup and storybook instructions into docs, added draft commit workflow doc.
Update to storybook welcome page.
> Itsadssd 25583 gp ux improvements to docs

- packages/storybook-html/.storybook/manager.js
- packages/storybook-html/.storybook/titleAddon.js
Followed the standard format specified for Title, "Page Title - Site Title - University of Queensland"
> Site title format changed

- README.md
- packages/storybook-html/src/docs/introduction/overview.story.mdx
Minor fixes to documentation based on feedback
> Itsadssd 25583 gp update documentation

- packages/storybook-html/.storybook/preview.js
- packages/storybook-html/src/components/body/body-elements.docs.mdx
- packages/storybook-html/src/components/body/body-utilities.docs.mdx
- packages/storybook-html/src/components/body/body.story.mdx
Body docs were regressed as a result of navigation changes in a previous PR.
> storybook-html: fix body docs

- packages/storybook-html/templates/component.docs.mdx
Review updates made to Initial draft of template for documentation of components in UQDS.
> Itsadssd 24094 template for documentation

- packages/previous-next/src/scss/_component.scss
- packages/storybook-html/src/components/previous-next/previous-next.docs.mdx
- packages/storybook-html/src/components/previous-next/previous-next.stories.js
- packages/storybook-html/src/components/progression/progression.docs.mdx
- packages/storybook-html/src/components/progression/progression.stories.js
- packages/storybook-html/src/components/table/table-card.html
- packages/storybook-html/src/components/table/table-irregular-headers.html
- packages/storybook-html/src/components/table/table-multi-level-headers.html
- packages/storybook-html/src/components/table/table-multiple-headers.html
- packages/storybook-html/src/components/table/table-with-classes.html
- packages/storybook-html/src/components/table/table.docs.mdx
- packages/storybook-html/src/components/table/table.html
- packages/storybook-html/src/components/table/table.stories.js
3 components, Prev-Next, Progression & Tables have been applied with the template documentation for components.
> Itsadssd 24094 apply documentation template

- packages/breadcrumb/src/scss/_component.scss
- packages/storybook-html/src/components/breadcrumb/breadcrumb.docs.mdx
- packages/storybook-html/src/components/breadcrumb/breadcrumb.stories.js
https://jira.its.uq.edu.au/jira/browse/ITSADSSD-28330
> Itsadssd 28330 fix breadcrumb white space

- packages/accordion/src/scss/_component.scss
- packages/card/src/scss/_component.scss
- packages/storybook-html/src/components/accordion/accordion.docs.mdx
- packages/storybook-html/src/components/accordion/accordion.stories.js
- packages/storybook-html/src/components/card/card.docs.mdx
- packages/storybook-html/src/components/card/card.html
- packages/storybook-html/src/components/card/card.stories.js
Accordion - display fix, doc added
Card - display fix, restructure, doc added 
(Card consolidate FS, CMS style guide is out of scope for now)
> Itsadssd 28865 fix display of components

- packages/storybook-html/src/components/intro/kitchen-sink.html
- packages/storybook-html/src/components/site-header/site-header.html
links changed from relative to absolute for 'site-header' component and kitchen sink example
> links changed from relative to absolute

- packages/grid/src/scss/_component.scss
- packages/grid/src/scss/_global.scss
- packages/storybook-html/src/components/grid/grid.docs.mdx
- packages/storybook-html/src/components/grid/grid.scss
- packages/storybook-html/src/components/grid/grid.stories.js
Expediting this PR. Fixing #164.
> ITSADSSD-30528 Fix full width grid margins urgent

- packages/form/src/scss/_component.scss
- packages/storybook-html/src/components/form/form-controls.docs.mdx
- packages/storybook-html/src/components/form/form-controls.stories.js
- packages/storybook-html/src/components/form/form-error-summary.story.mdx
- packages/storybook-html/src/components/intro/kitchen-sink.html
Form component prefixed 
Pane component in kitchen sink prefixed
> Itsadssd 31419 uq prefixing

- packages/accordion/README.md
- packages/accordion/package.json
- packages/accordion/src/scss/_component.scss
- packages/breadcrumb/README.md
- packages/breadcrumb/package.json
- packages/breadcrumb/src/scss/_component.scss
- packages/grid-menu/README.md
- packages/grid-menu/src/scss/_component.scss
- packages/header/README.md
- packages/header/package.json
- packages/header/src/scss/_component.scss
- packages/previous-next/README.md
- packages/previous-next/package.json
- packages/previous-next/src/scss/_component.scss
- packages/side-nav/README.md
- packages/side-nav/package.json
- packages/side-nav/src/scss/_component.scss
- packages/site-header/README.md
- packages/site-header/package.json
- packages/site-header/src/scss/_component.scss
- packages/storybook-html/src/components/side-nav/side-nav-multi-level.html
- packages/storybook-html/src/docs/introduction/get-started.story.mdx
Replaced SVG code with icon component implementation
> Itsadssd 31421 icon code check

- packages/header/src/scss/_component.scss
> fixed incorrect icon colour.

- packages/header/src/js/header.js
Looks like Safari doesn't like setting the focus in a callback
> Show keyboard when toggling search on iOS 

- packages/footer/src/scss/_component.scss
Fixes footer icons changing size on hover when viewed in safari
> fixed size change on safari

- packages/footer/src/scss/_component.scss
Updated gradient colour to be more accurate across full transition
> update gradient colour

- package-lock.json
- packages/private-design-output/src/example.html
- packages/private-design-output/src/homepage.html
- packages/storybook-html/src/components/header/header.docs.mdx
- packages/storybook-html/src/components/header/header.html
Replaces mega menu <nav> elements with <div> 
These were incorrectly reverted in one of the merges
> Fix incorrect nav to div

- packages/storybook-html/src/components/header/header.stories.js
- packages/storybook-html/src/components/site-header/site-header.stories.js
Updated storybook JS for Header and Site Nav to correctly pass dom elements
> updated JS calls

- packages/site-header/src/scss/_component.scss
Creates a temporary fix for the Site header Dropdown
> update to site header

- packages/header/src/scss/_component.scss
Fixes wrapping title on mobile menu
> mobile title wrap fix

- packages/site-header/src/scss/_global.scss
Updating the Site header menu width from 320px to 400px
> Site header updated width

- packages/private-design-output/src/interim.html
- packages/storybook-html/stories/components/accordion/accordion.docs.mdx
- packages/storybook-html/stories/components/header/header.docs.mdx
- packages/storybook-html/stories/components/site-header/site-header.docs.mdx
Updated initialise script for Site Header
Added documentation for
Accordion
Header
Site Header
> Itsadssd 40640 initialise script

- packages/accordion/package.json
Without this @rollup/plugin-node-resolve can't find the code to bundle
> Fix path to main

- packages/accordion/src/scss/_component.scss
- packages/storybook-html/stories/components/accordion/accordion.stories.js
- Add configurable accordion tag story - allows changing the tag from storybook UI
- Remove padding on children of toggle
> Accordion styling when using h2-h5

- .github/workflows/publish.yml
- lerna.json
- packages/accordion/README.md
- chore(ci): Fix ref
- chore(ci): More CI changes
- docs(accordion): Docs update
> docs(accordion): Update accordion docs

- .npmrc
- packages/accordion/README.md
- chore(ci): Force https for repo
- docs(accordion): Accordion docs
> docs(accordion): Accordion docs

- .github/workflows/publish.yml
- lerna.json
- chore(ci): Remove skip ci
- Revert "chore: Persist credentials (#470)"
> chore(ci): Alternate CI approach

- packages/layout/src/scss/_container.scss
- packages/layout/src/scss/_custom-properties.scss
- packages/layout/src/scss/_sections.scss
- packages/layout/src/scss/_sidebar-layout.scss
- packages/navigation/src/scss/_local-nav.scss
A couple of fixes that got picked up whilst integrating components in Drupal.
> Layout custom property fixes + local nav child selector fix

- packages/hero/src/scss/_custom-properties.scss
- packages/hero/src/scss/_hero-basic.scss
- packages/hero/src/scss/_hero.scss
Ensures we have namespaced custom properties that won't conflict in drupal.
Fixes hero font size as per Lauras feedback.
> Hero font size fixes

- packages/layout/src/scss/_sidebar-layout.scss
- packages/sections/src/scss/_component.scss
- packages/storybook-html/stories/templates/home.stories.js
- packages/storybook-html/stories/templates/level1.stories.js
- packages/storybook-html/stories/templates/level2.stories.js
Two small fixes that came up in QA.
> Local nav + Section QA fixes

- packages/card/src/scss/_card.scss
> [ITSADSSD-55779] Icon nav fix

- packages/hero/src/scss/_custom-properties.scss
- packages/navigation/src/scss/_local-nav.scss
- packages/sections/src/scss/_custom-properties.scss
- packages/sections/src/scss/_sections.scss
- packages/storybook-html/stories/layout/card-grid/card-grid.stories.js
- packages/storybook-html/stories/layout/page-layouts/sidebar/sidebar.stories.js
> fix: further spacing fixes

- packages/private-design-output/src/example.html
- packages/private-design-output/src/homepage.html
- packages/private-design-output/src/interim.html
- packages/storybook-html/stories/components/header/header-interim.html
- packages/storybook-html/stories/components/header/header.html
- packages/storybook-html/stories/components/header/header.stories.js
- packages/storybook-html/stories/deprecated/header-legacy/header.html
- packages/storybook-html/stories/deprecated/header-legacy/header.mdx
- packages/storybook-html/stories/deprecated/header-legacy/header_no-local-search.html
Removed name="op" from Submit button. 
Removes from URL **&op=search**
https://www.uq.edu.au/search/?q=math&op=Search&as_sitesearch=library.uq.edu.au
Becomes
https://www.uq.edu.au/search/?q=math&as_sitesearch=library.uq.edu.au
> Removing OP var from search

- packages/storybook-html/stories/components/core/written-style.html
- packages/storybook-html/stories/introduction/get-started.mdx
- packages/storybook-html/stories/introduction/overview.stories.js
> ITSADSSD-60052 content updates

- lerna.json
- package-lock.json
- package.json
Lerna update was failing. i have rolled it back for the moment until we can determine where the issue is.
> chore: Lerna roll back

- packages/pane/src/scss/_pane.scss
- packages/storybook-html/stories/components/pane/pane.stories.js
- packages/storybook-html/stories/layout/card-grid/card-grid.stories.js
- scripts/screenshot.config.json
> ITSADSSD-59302: Video pane

- packages/form/package.json
- packages/form/src/js/main.js
- packages/form/src/js/search-input.js
- packages/form/src/scss/_component.scss
- packages/form/src/scss/_search-input.scss
- packages/form/src/scss/main.scss
- packages/storybook-html/.storybook/preview.js
- packages/storybook-html/stories/components/form/form.scss
- packages/storybook-html/stories/components/search-input/search-input.stories.js
- packages/storybook-html/stories/templates/News/news-home.stories.js
- scripts/screenshot.config.json
> ITSADSSD-59530: Search input component + ITSADSSD-59301: Search block

- packages/layout/src/scss/_sidebar-right-layout.scss
- packages/social/src/js/social-share.js
- packages/social/src/scss/_social-share.scss
- packages/storybook-html/stories/components/social-share/social-share.stories.js
Bug fixes for:
https://jira.its.uq.edu.au/jira/browse/ITSADSSD-59298 and https://jira.its.uq.edu.au/jira/browse/ITSADSSD-60374
> ITSADSSD-59298 + ITSADSSD-60374: Bug fixes

- packages/storybook-html/stories/templates/News/news-article.stories.js
> [ITSADSSD-59774]: Add link tag to news article header

- packages/layout/src/scss/_container.scss
> [ITSADSSD-62066]: overflow-x clip for containers to prevent scrollbars/overflow

- packages/button/src/scss/_component.scss
Fix to button alignment of icons.
> ITSADSSD-58562: Button alignment

- packages/core/src/scss/_partials/_colour-constants.scss
- packages/storybook-html/stories/components/core/_colour.scss
- packages/storybook-html/stories/components/core/colour.stories.js
> ITSADSSD-61845: add grey-925 color

- packages/card/src/scss/_card.scss
- packages/card/src/scss/_story-card.scss
https://jira.its.uq.edu.au/jira/browse/ITSADSSD-60968
> [ITSADSSD-60968] Removed line clamp from standard cards

- .github/workflows/publish-preview.yml
- .github/workflows/publish-sb.yml
- .github/workflows/reg.yml
- packages/pagination/package.json
- packages/storybook-html/.storybook/main.js
What this change does
- Deploys a new `storybook-react` build for react components. 
- Implements storybook composition into `storybook-html`
- setup new deployment process for both storybooks.
Additional changes
- Included a main.css file with that will include all styles for all components. However this won't be used in any of the Drupal sites as we'll be using individual stylesheets from each @uqds package.
- There are some limited docs which can be expanded on later on.
- The included UqCard component isn't complete and is just added as a POC.
You can run both storybooks locally from root (in single terminal sessions): 
```
npm run storybook
```
To run locally (in two seperate terminal sessions):
```
cd packages/storybook-react
npm run storybook
```
```
cd packages/storybook-html
npm …
```
> ITSADSSD-59698 composition build

- packages/pagination/src/scss/_custom-properties.scss
- packages/pagination/src/scss/_pagination.scss
https://www.figma.com/design/qu9EgKRibnXMeVbRHMLRRu/News-UI?node-id=4754-3137
> ITSADSSD-61343: Improve mobile breakpoint in pagination
